spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 696666858656-qkjnjvkvgg619odd03l31g9ffikt493l.apps.googleusercontent.com
            client-secret: uWvPd9cSdpxO29reKjYE5vAg
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
              - openid